# é»˜è®¤é…ç½®æ–‡ä»¶

baseURL: /
languageCode: zh-Hans
title: Naldo's Blog
theme: "PaperMod"
enableEmoji: true
enableGitInfo: true
hasCJKLanguage: true
defaultContentLanguage: zh
timeZone: Asia/Shanghai

params:
  description: å‘œå•¦å•¦çš„æŠ€æœ¯æ ˆCode
  title: çº³å¤šçš„åšå®¢
  # ä¸»é¢˜
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowCodeCopyButtons: true

  # homeInfoæ¨¡å¼
  homeInfoParams:
    Title: ğŸš€å‘œå•¦å•¦çš„æŠ€æœ¯æ ˆğŸ¸
    Content: <Let's Code/>

  # ç¤¾äº¤å›¾æ ‡
  socialIcons:
    - name: github
      url: "https://github.com/uestcNaldo"
    - name: twitter
      url: "https://twitter.com/Naldo_1295"

  # ç¼–è¾‘æ–‡ç« é“¾æ¥
  editPost:
    URL: "https://github.com/uestcNaldo/blog-naldo/tree/master/content"
    Text: "Githubç¼–è¾‘"
    appendFilePath: true


menu:
  main:
    - identifier: search
      name: æœç´¢
      pre: 
      url: /search/
      weight: -10
    - identifier: categories
      name: åˆ†ç±»
      url: /categories/
      weight: 10
    - identifier: tags
      name: æ ‡ç­¾
      url: /tags/
      weight: 20
    - identifier: archives
      name: å½’æ¡£
      url: /archives/
      weight: 30
    - identifier: github
      name: Github
      url: "https://github.com/uestcNaldo/blog-naldo"
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
